// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleServiceBook.Models.Domains;

#nullable disable

namespace VehicleServiceBook.Migrations
{
    [DbContext(typeof(VehicleServiceBookContext))]
    partial class VehicleServiceBookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleServiceBook.Models.Domains.Booking", b =>
                {
                    b.Property<int>("Bookingid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Bookingid"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("MechanicId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceCenterId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("TimeSlot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Bookingid")
                        .HasName("PK__Booking__73961EC5AADDA612");

                    b.HasIndex("MechanicId");

                    b.HasIndex("ServiceCenterId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Booking", (string)null);
                });

            modelBuilder.Entity("VehicleServiceBook.Models.Domains.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("PaymentStatus")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<int?>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("InvoiceId")
                        .HasName("PK__Invoice__D796AAB53CBEA5AA");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasFilter("[BookingId] IS NOT NULL");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("Invoice", (string)null);
                });

            modelBuilder.Entity("VehicleServiceBook.Models.Domains.Mechanic", b =>
                {
                    b.Property<int>("Mechanicid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mechanicid"));

                    b.Property<string>("Expertise")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MechanicName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ServiceCenterId")
                        .HasColumnType("int");

                    b.HasKey("Mechanicid")
                        .HasName("PK__Mechanic__6B0509C9F62A2D41");

                    b.HasIndex("ServiceCenterId");

                    b.ToTable("Mechanic", (string)null);
                });

            modelBuilder.Entity("VehicleServiceBook.Models.Domains.Registration", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId")
                        .HasName("PK__Registra__1788CC4C88AA8157");

                    b.HasIndex(new[] { "Email" }, "UQ__Registra__A9D10534FDAE5997")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Registration", (string)null);
                });

            modelBuilder.Entity("VehicleServiceBook.Models.Domains.ServiceCenter", b =>
                {
                    b.Property<int>("ServiceCenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceCenterId"));

                    b.Property<string>("ServiceCenterContact")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ServiceCenterLocation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ServiceCenterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ServiceCenterId")
                        .HasName("PK__ServiceC__71B62BE31C4F7EA0");

                    b.HasIndex("UserId");

                    b.ToTable("ServiceCenter", (string)null);
                });

            modelBuilder.Entity("VehicleServiceBook.Models.Domains.ServiceType", b =>
                {
                    b.Property<int>("ServiceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceTypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ServiceTypeId")
                        .HasName("PK__ServiceT__8ADFAA6C2546C593");

                    b.ToTable("ServiceType", (string)null);
                });

            modelBuilder.Entity("VehicleServiceBook.Models.Domains.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("VehicleId")
                        .HasName("PK__Vehicle__476B5492C88E34FF");

                    b.HasIndex("UserId");

                    b.ToTable("Vehicle", (string)null);
                });

            modelBuilder.Entity("VehicleServiceBook.Models.Domains.Booking", b =>
                {
                    b.HasOne("VehicleServiceBook.Models.Domains.Mechanic", "Mechanic")
                        .WithMany()
                        .HasForeignKey("MechanicId")
                        .HasConstraintName("Fk_Booking_Mechanic");

                    b.HasOne("VehicleServiceBook.Models.Domains.ServiceCenter", "ServiceCenter")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceCenterId")
                        .HasConstraintName("FK_Booking_ServiceCenter");

                    b.HasOne("VehicleServiceBook.Models.Domains.ServiceType", "ServiceType")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Booking_ServiceType");

                    b.HasOne("VehicleServiceBook.Models.Domains.Registration", "Registration")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Booking_Registration");

                    b.HasOne("VehicleServiceBook.Models.Domains.Vehicle", "Vehicle")
                        .WithMany("Bookings")
                        .HasForeignKey("VehicleId")
                        .HasConstraintName("FK_Booking_Vehicle1");

                    b.Navigation("Mechanic");

                    b.Navigation("Registration");

                    b.Navigation("ServiceCenter");

                    b.Navigation("ServiceType");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleServiceBook.Models.Domains.Invoice", b =>
                {
                    b.HasOne("VehicleServiceBook.Models.Domains.Booking", "Booking")
                        .WithOne("Invoice")
                        .HasForeignKey("VehicleServiceBook.Models.Domains.Invoice", "BookingId")
                        .HasConstraintName("FK_Invoice_Booking");

                    b.HasOne("VehicleServiceBook.Models.Domains.ServiceType", "ServiceType")
                        .WithMany("Invoices")
                        .HasForeignKey("ServiceTypeId")
                        .HasConstraintName("FK_Invoice_ServiceType");

                    b.Navigation("Booking");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("VehicleServiceBook.Models.Domains.Mechanic", b =>
                {
                    b.HasOne("VehicleServiceBook.Models.Domains.ServiceCenter", "ServiceCenter")
                        .WithMany("Mechanics")
                        .HasForeignKey("ServiceCenterId")
                        .HasConstraintName("FK_Mechanic_ServiceCenter");

                    b.Navigation("ServiceCenter");
                });

            modelBuilder.Entity("VehicleServiceBook.Models.Domains.ServiceCenter", b =>
                {
                    b.HasOne("VehicleServiceBook.Models.Domains.Registration", "User")
                        .WithMany("ServiceCenters")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__ServiceCe__UserI__3A81B327");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleServiceBook.Models.Domains.Vehicle", b =>
                {
                    b.HasOne("VehicleServiceBook.Models.Domains.Registration", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Vehicle_Registration");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleServiceBook.Models.Domains.Booking", b =>
                {
                    b.Navigation("Invoice")
                        .IsRequired();
                });

            modelBuilder.Entity("VehicleServiceBook.Models.Domains.Registration", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ServiceCenters");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("VehicleServiceBook.Models.Domains.ServiceCenter", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Mechanics");
                });

            modelBuilder.Entity("VehicleServiceBook.Models.Domains.ServiceType", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("VehicleServiceBook.Models.Domains.Vehicle", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
